---
- name: Create vSphere Distributed Switch and Add Port Groups
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: vcenter_hostname
      prompt: "Enter vCenter Hostname (e.g., 10.9.20.75)"
      private: false

    - name: vcenter_username
      prompt: "Enter vCenter Username (e.g., administrator@vsphere.local)"
      private: false

    - name: vcenter_password
      prompt: "Enter vCenter Password"
      private: true

    - name: datacenter_name
      prompt: "Enter Datacenter Name (e.g., pod10-vcsa)"
      private: false

    - name: vds_name
      prompt: "Enter Distributed Switch Name (e.g., ansible-dvs)"
      private: false

    - name: validate_certs
      prompt: "Validate vCenter Certificates? (true/false)"
      private: false
      default: false

  vars:
    vds_version: "8.0.0"
    vds_uplink_ports: 2
    port_groups:
      - name: "Web_PortGroup"
        vlan_id: 10
        port_binding: "static"
      - name: "App_PortGroup"
        vlan_id: 20
        port_binding: "static"
      - name: "DB_PortGroup"
        vlan_id: 30
        port_binding: "static"

  tasks:
    - name: Debug vCenter Credentials
      debug:
        msg: "Connecting to vCenter at {{ vcenter_hostname }} with user {{ vcenter_username }}"

    - name: Create vSphere Distributed Switch
      community.vmware.vmware_dvswitch:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter_name: "{{ datacenter_name }}"
        switch_name: "{{ vds_name }}"
        version: "{{ vds_version }}"
        uplink_quantity: "{{ vds_uplink_ports }}"
        state: present
      delegate_to: localhost

    - name: Add Port Groups to Distributed Switch
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        switch_name: "{{ vds_name }}"
        portgroup_name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        port_binding: "{{ item.port_binding }}"
        state: present
      loop: "{{ port_groups }}"
      delegate_to: localhost

