---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "10.9.20.75"
    vcenter_user: "administrator@penlabs.net"
    vcenter_pass: "Pensando0$"
    datacenter_name: "pod10-vcsa"
    esxi_hostname: "10.9.23.217"
    #cluster_name: "Cluster"
  tasks:
  - name: Clone the template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: web02
      template: TinyLinuxBash-temp
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm/ansible-vm
      esxi_hostname: "{{ esxi_hostname }}"
      #cluster: "{{ cluster_name }}"
      datastore: "datastore-217-2"
      networks:
      - name: pod10-dvs-pvlan-2095
        ip: 10.29.95.160
        netmask: 255.255.252.0
        gateway: 10.9.23.254
        type: static
        dns_servers: 8.8.8.8
      customization:
        hostname: "web02"
        dns_servers:
        - 8.8.8.8
        - 10.9.20.7
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
