---
- name: Safely delete VMs from vSphere with confirmation
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "10.9.20.75"
    vcenter_user: "administrator@penlabs.net"
    vcenter_pass: "Pensando0$"
    datacenter_name: "pod10-vcsa"

    vm_list:
      - name: web02
      - name: web03

  tasks:
    - name: Prompt before deletion
      pause:
        prompt: "Do you really want to delete all listed VMs? Type 'yes' to proceed"
      register: delete_prompt

    - name: Check user confirmation
      fail:
        msg: "VM deletion cancelled by user."
      when: delete_prompt.user_input | lower != 'yes'

    - name: Check if each VM exists
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.name }}"
        validate_certs: false
      register: vm_info
      loop: "{{ vm_list }}"
      loop_control:
        label: "{{ item.name }}"
      ignore_errors: yes
      delegate_to: localhost

    - name: Delete VMs only if they exist
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.item.name }}"
        state: absent
        force: yes
      when: (item.failed is not defined or item.failed == false) and (item.instance is defined)
      loop: "{{ vm_info.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      delegate_to: localhost

